# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 江涛
subtitle: 记录成长，共同进步
description: 沉淀下来，你想要的时间会给你
remark: 常年承接h5,小程序,node，中后台，爬虫等外包
author: f2ecoder@vip.qq.com
language: zh-Hans

timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://imjiangtao.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

hexoWorkbox:
  enable: true
workbox:
  swDest: 'sw.js'
  importScripts: 
    - 'https://g.alicdn.com/kg/workbox/3.3.0/workbox-sw.js'
  globPatterns:
    - '**/*.{html,js,css,svg,jpeg,jpg,png,gif}'
  runtimeCaching:
    - urlPattern: '**/*.{html,js,css,svg,jpeg,jpg,png,gif}'
      handler: 'staleWhileRevalidate'
      options:
        cacheName: 'precache'
  skipWaiting: true
  clientsClaim: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
plugin:
 - hexo-generator-feed

theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:


avatar: https://avatars1.githubusercontent.com/u/2155745?s=460&v=4

# Social links
social:
  GitHub: https://github.com/jiangtao
  ZhiHu: http://www.zhihu.com/people/Jerret321

# Blog rolls
links_title: 友情链接
links_layout: inline
links:
  

# https://segmentfault.com/a/1190000016286007 pwa
# https://github.com/josex2r/hexo-workbox workbox 